### PR TITLE
Fix #10 - By adapting to the new Flay 2.8.0 api

### LINKED ISSUE #10: Bug: pronto/flay does not respect values in `.flayignore`
To reproduce the issue follow the steps in the repository: [mknapik/pronto-flay-ignore-issue](https://github.com/mknapik/pronto-flay-ignore-issue).

`.flayignore` contents:

```
spec/**/*.rb
```

```bash
$ flay .
```

returns

```
Total score (lower is better) = 64

1) Similar code found in :defs (mass = 64)
  lib/duplication.rb:2
  lib/duplication.rb:8
```

```bash
$ pronto run -r flay -c 596484d
```

returns

```
lib/duplication.rb:2 W: Similar code found in duplication.rb:2, duplication.rb:8
lib/duplication.rb:8 W: Similar code found in duplication.rb:2, duplication.rb:8
spec/duplication_spec.rb:14 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
spec/duplication_spec.rb:21 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
spec/duplication_spec.rb:28 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
spec/duplication_spec.rb:35 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
spec/duplication_spec.rb:42 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
spec/duplication_spec.rb:49 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
```

I believe the issue lies in the fact that `flay` uses relative paths (`String` array though I've checked relative `Pathname`s and it works as well) and `pronto/flay` passes absolute paths (`Pathname` objects).

So actually running flay with absolute paths does not respect `.flayignore` as well.

```bash
flay `pwd`/
```

```
Total score (lower is better) = 178

1) Similar code found in :iter (mass = 114)
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:14
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:21
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:28
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:35
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:42
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:49

2) Similar code found in :defs (mass = 64)
  /tmp/pronto-flay-ignore-issue/lib/duplication.rb:2
  /tmp/pronto-flay-ignore-issue/lib/duplication.rb:8
```

So actually I'm not sure whether we should fix `pronto-flay` and pass relative paths or fix `flay` itself to recognise absolute paths.
@mmozuras @seattlerb What do you think?

### PR DESCRIPTION
**Pull request by abinoam**
Fix #10 
A limitation that I could see is that files at .flayignore should be preceded by double asteriks like
```
**/spec/hello.rb
```

### CODE REVIEW

**Comment by abinoam** [comment]
Rebased and git push forced to fix tests. Waiting for travis.

**Comment by abinoam** [comment]
Hi @mmozuras, could you have a look at this PR when you have some time please?

**Comment by mknapik** [comment]
@abinoam I guess we should lock `flay` to version `~> 2.8.0` in the gemspec, shouldn't we?

File: lib/pronto/flay.rb [hunk 1]
```diff
@@ -3,19 +3,27 @@
...
       files = ruby_patches.map(&:new_file_full_path)
-      files = ::Flay.filter_files(files)
 
       if files.any?
-        flay.process(*files)
+        # The current Flay (2.8.0) takes care of filtering
+        # files by looking at .flayignore.
+        # Saving the returned Flay object at @flay so we
+        # can inspect it and build the messages Array.
+        self.flay = ::Flay.run(files)
```
Comment (mmozuras) [inline lib/pronto/flay.rb]: Not a fan of this pattern with `attr_writer`. Maybe we can improve it to something like:

```ruby
def flay
  @flay ||= ::Flay.run(files)
end

def files
  ruby_patches.map(&:new_file_full_path)
end
```

This is now possible, because `ruby_patches` is just a `Runner` method 😄

**Comment by mmozuras** [comment]
@mknapik is correct. We should do:

```ruby
  s.add_dependency('flay', '~> 2.8', '>= 2.8.0')
```

**Comment by abinoam** [comment]
Perfect @mknapik !

I'll try to upgrade the PR now.

**Comment by abinoam** [comment]
@mmozuras and @mknapik 

Could it be just ?
```gemspec
  s.add_dependency('flay', '~> 2.8')
```

Without the ```>= 2.8``` ?

By the way, I was looking at the current dependency set and I'm not understanding it.
```gemspec
s.add_dependency('flay', '~> 2.7', '>= 2.6.0')
```

It say 2.7 onward till <= 2.8 (with the tilde).
But it also says that >= 2.6.0 works.

**Comment by abinoam** [comment]
... it was introduced here 7fb3dbe0a902aea2b78d518102d9b80b7531da24
Just a typo?

**Comment by abinoam** [comment]
References: 
* https://robots.thoughtbot.com/rubys-pessimistic-operator
* http://guides.rubygems.org/patterns/#semantic-versioning

**Comment by mknapik** [comment]
@abinoam 
Not sure about the current lock. However, regarding the new dependency @mmozuras proposal looks legit.

**Comment by abinoam** [comment]
Could explain me how it "reads" ? @mknapik 

```
 s.add_dependency('flay', '~> 2.8', '>= 2.8.0')
```

I'm "reading" it like. 
(~> 2.8) - _Accept 2.x.x greater than 2.8.0 but not 2.9_
(>= 2.8.0) - _Accept any version greater than 2.8.0, as 2.9, 2.10, 3.1 etc_

I'm a little confused.

**Comment by mknapik** [comment]
You're reading it correct.

Although, I guess the following:
```
 s.add_dependency('flay', '>= 2.8.0')
```
will have pretty much the same effect.

**Comment by abinoam** [comment]
Right.
The ```~> 2.8 ``` has the same effect as ```['>= 2.8.0', '< 2.9.0']```. And the ideia behind it is to protect against features changes that may be incompatible with the *minor* releases _2.x.0_. Minor releases should have *compatible* apis. But, we may be using things that are not _public_ so they may change in minor releases.

From http://guides.rubygems.org/patterns/#semantic-versioning
* PATCH 0.0.x level changes for implementation level detail changes, such as small bug fixes
* MINOR 0.x.0 level changes for any backwards compatible API changes, such as new functionality/features
* MAJOR x.0.0 level changes for backwards incompatible API changes, such as changes that will break existing users code if they update

If we can "vote" for this, I vote for ```~> 2.8``` only.
It protects against breaking changes in Flay.
So, when Flay upgrades, developers have time to check if things are still working.

**Comment by abinoam** [comment]
I have pushed 2 more commits with the suggestions. If ready, feel free to merge it (or not).
If you think we should use a different version constraint in gemspec, just drop a line and I'll rebase it.
👍

**Comment by mmozuras** [comment]
Thanks for the contribution!

I'll merge it and release a new version 👏

File: lib/pronto/flay.rb [hunk 2]
```diff
@@ -4,20 +4,27 @@
...
+    #
+    # Coercing files with Array to protect against
+    # +nil+ values.
     def flay
-      @flay ||= ::Flay.new
+      @flay ||= ::Flay.run(Array(files))
+    end
+
+    def files
+      @files ||= ruby_patches.map(&:new_file_full_path)
```
Comment (zenspider) [inline lib/pronto/flay.rb]: Since this is the result of a `map`, do you really need the `Array` call above?

Comment (abinoam) [inline lib/pronto/flay.rb]: Hi Ryan, you could also be nicknamed Zeneagle (with eagle's eye).
You're great! 👏 

I really don't remember why I have put this Array call, so I think you're right.
There's no need for it.
Thank you for spotting it
